/**
 * @file SX1278_hw.h
 * @brief Hardware abstraction for an Ai-Thinker LoRa-02 (SX1278) on SAM D21.
 */

#ifndef SX1278_HW_H
#define SX1278_HW_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * The board connections are generated by MPLAB Harmony as:
 *   PA16 - SERCOM1 PAD0 - MOSI
 *   PA17 - SERCOM1 PAD1 - SCK
 *   PA19 - SERCOM1 PAD3 - MISO
 *   PA18 - GPIO          - NSS
 *   PA10 - GPIO          - RESET
 *   PA11 - GPIO          - DIO0
 *
 * The pins and SPI instance are fixed by the Harmony configuration, therefore
 * the hardware object only acts as an instance handle for the portable driver.
 */
typedef struct
{
    uint8_t reserved;
} SX1278_hw_t;

/** Initialize the GPIO interface and reset the SX1278. */
void SX1278_hw_init(SX1278_hw_t *hw);

/** Drive NSS high when value is 1, low otherwise. */
void SX1278_hw_SetNSS(SX1278_hw_t *hw, int value);

/** Apply the active-low hardware reset pulse. */
void SX1278_hw_Reset(SX1278_hw_t *hw);

/** Send one byte over SERCOM1 SPI while keeping NSS asserted. */
void SX1278_hw_SPICommand(SX1278_hw_t *hw, uint8_t cmd);

/** Clock and return one byte over SERCOM1 SPI while keeping NSS asserted. */
uint8_t SX1278_hw_SPIReadByte(SX1278_hw_t *hw);

/** Blocking millisecond delay for the bare-metal application. */
void SX1278_hw_DelayMs(uint32_t msec);

/** Return the current DIO0 GPIO level. */
int SX1278_hw_GetDIO0(SX1278_hw_t *hw);

#ifdef __cplusplus
}
#endif

#endif /* SX1278_HW_H */
